### ISSUE TITLE
El punto 10.1 directamente creo que no esta hecho

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#11]
Me da solo a elegir por categorias pero me da los servicios
An actor who is not authenticated must be able to:
1. List the rendezvouses in the system grouped by category.

**Comment by fraagucan2** [comment]
Tras hablar con el ingeniero de requisitos se ha llegado a la conclusión de que el requisito 10.1 era una errata y lo que realmente el cliente deseaba era: listado de servicios agrupados por categorías.
