### ISSUE TITLE
Al elegir el padre de una categoria no hay diferencias si dos categorias se llaman iguales

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#16]
Lo suyo sería poder diferenciarlas en el select de alguna forma

**Comment by GuillermoCasalCaro** [comment]
<form:label path="categoryFather">
		<spring:message code="category.father" />:
	</form:label>
	<form:select path="categoryFather">
		<form:option value="0" label="-"/>
		<jstl:forEach items="${categories}" var="cat">
			<jstl:if test="${not empty cat.categoryFather}">
				<form:option value="${cat.id}" label="${cat.categoryFather.name} -> ${cat.name}"/>
			</jstl:if>
			<jstl:if test="${empty cat.categoryFather}">
				<form:option value="${cat.id}" label="${cat.name}"/>
			</jstl:if>
		</jstl:forEach>
<%-- 		<form:options items="${categories}" itemLabel="categoryFather" itemValue="id"/> --%>
	</form:select>
	<form:errors cssClass="error" path="categoryFather" />
	<br />
	<br />

**Comment by GuillermoCasalCaro** [comment]
![image](https://user-images.githubusercontent.com/18685581/37713341-eba0b1c6-2d16-11e8-804b-5ddf11e56c35.png)
