### ISSUE TITLE
Como menor de edad no me aparecen si quiera las rendezvous para adultos, entonces para que tenemos la columna que da información sobre ello?

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#19]
Si me autentico como user3 que es menor no sale las rendezvous de adultos, pero entonces seria absurdo una columna que me informa sobre si es para mayores de edad o no, ya que si soy mayor de edad puedo entrar a todas y si soy menor no me aparecen, yo vería que sea menor o mayor me aparezcan todas pero solo pueda asistir a las de menor de edad

**Comment by jullopjim1** [comment]
esq en los requisitos pone que a los menores no se les puede mostrar la de adultos, y la columna esta para diferencia las de adultos y la que no a los mayores de edad.
