### ISSUE TITLE
Aparece la vista de comentar en otro rendezvous que no sea de mis rsvp

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#20]
No me deja guardarlo pero no se hasta que punto el hecho de que si aparezca la vista y pueda meter valores esta bien o mal
![image](https://user-images.githubusercontent.com/33448873/37618477-ace32cd6-2bb6-11e8-88ea-1d6ce06f965c.png)

**Comment by ordomedina** [comment]
No pasa nada mientras al final no te deje hacer el comentario
