### ISSUE TITLE
Problemas con las cookies de la tarjeta de crédito

### ISSUE THREAD

**Issue by ordomedina** [JJCCGGRR24/Firulais-2.0#26]
Si solicitas un servicio logueado como user1 e introduces una tarjeta de crédito, al solicitar después otro servicio logueado como user2 ya te aparecen los datos de la tarjeta de crédito del user1

**Comment by GuillermoCasalCaro** [comment]
Hecho!

![imagen](https://user-images.githubusercontent.com/18685581/37742363-90b24500-2d65-11e8-9fb0-24be05483179.png)

![imagen](https://user-images.githubusercontent.com/18685581/37742378-a1f8d31a-2d65-11e8-9df3-bf09e26ffb76.png)
