### ISSUE TITLE
Al seleccionar un servicio a la hora de request me aparece para seleccionar un servicio que ya tengo solicitado y el error que aparece no es muy intuitivo

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#27]
o carmbiar el error o que no aparezcan esos servicios en la lista

**Comment by GuillermoCasalCaro** [comment]
![image](https://user-images.githubusercontent.com/18685581/37822114-d6d70cfc-2e85-11e8-8170-62296a5390f7.png)
Ya no aparecen, esto estaba hecho, pero cuando lo cambiaste para que solo salgan los visibles se te olvido quitar los que ya tiene el rendezvous.
