### ISSUE TITLE
si quieres linkar a un rendezvous cuando esta en final mode da un errror en la base de datos

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#30]
Dos opciones o cambiar ese error a uno que t diga que no se puede linkar porque el rendezvous esta en version defitiiva o capar el boton de linkar si ya es version definitiva

**Comment by JJCCGGRR24** [comment]
entro como user1 e intento linkar al rendezvous de nombre Cacuacoatl cualquier otro rendezvous.

![image](https://user-images.githubusercontent.com/33448873/37801155-c74413f8-2e25-11e8-8e83-e54bbc7bd115.png)

**Comment by GuillermoCasalCaro** [comment]
![image](https://user-images.githubusercontent.com/18685581/37818321-0c6ef2b4-2e7a-11e8-801c-a7e9abaedc30.png)
