### ISSUE TITLE
Mostrar las fechas correctamente y no con tantos ceros y tal

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#31]

**Comment by GuillermoCasalCaro** [comment]
Ok para esto tan solo importar:

<%@taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>

y poner:

<fmt:formatDate value="${article.moment}" pattern="dd/MM/yy HH:mm"/>

**Comment by GuillermoCasalCaro** [comment]
Para listados añadir a la columna:

format="{0,date,dd/MM/yy HH:mm}"

**Comment by JJCCGGRR24** [comment]
Faltaria Chirp que lo hace guille y la vrrdad los details muestran la fecha a pelo no se como internacionalizar eso
