### ISSUE TITLE
Al darle al details de newspaper/list.do desde no autenticado peta

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#33]
![image](https://user-images.githubusercontent.com/33448873/38494706-2b2428d4-3bf7-11e8-9aea-28299827cc98.png)

**Comment by fraagucan2** [comment]
no es el list, es el details.do

**Comment by fraagucan2** [comment]
He añadido ese try para trabajar con loginService en el caso de que el usuario este logueado.

![imagen](https://user-images.githubusercontent.com/22836642/38495913-b98cabce-3bfb-11e8-9ae4-1ae3a1550eff.png)
