### ISSUE TITLE
CUando entro como user1 a la opcion del header user e interactuo me redirige donde no debe

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#35]
se ve que hay dos vistas para lo mismo y no se redirigen donde deben
Cuando pulso USERS en el header:
![image](https://user-images.githubusercontent.com/33448873/38497049-ffcda792-3bff-11e8-83ee-9ff00d9699dc.png)

Despues de entrar en el perfil de un user y darle al boton back:
![image](https://user-images.githubusercontent.com/33448873/38497065-11999b0c-3c00-11e8-8113-15d662e7d6fd.png)

**Comment by fraagucan2** [comment]
No lo veo mal. Creo que debe ser asi.

**Comment by JJCCGGRR24** [comment]
no puede estar bien porque primero dice que los sigo y luego que no los sigo

**Comment by JJCCGGRR24** [comment]
Cambiado el boton back de la vista user/list y ahora al volver es a la misma vista
