### ISSUE TITLE
A mys newspapers cambiarle el nombre del titulo pues es confunsoal tener otra vista con el mismo titulo pero distinto significado

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#37]
![image](https://user-images.githubusercontent.com/33448873/38497162-7580c564-3c00-11e8-8e31-d299b1b53548.png)
 Cambiar de Newspaper list a My newspaper o algo asi

**Comment by fraagucan2** [comment]
no veo confusion, es un listado de newspapers, sea mio o no, es un listado

**Comment by JJCCGGRR24** [comment]
hombre yo veo mejor porque  aunque sean ambos listados de newspaper lo suyo seria que te especifique cuando estas en la global o en las tuya

**Comment by fraagucan2** [comment]
Arreglao. (He añadido una nueva entrada en el tiles para cambiar el titulo a la vista)

![imagen](https://user-images.githubusercontent.com/22836642/38504191-4fa9d164-3c14-11e8-9c4e-cb374e99c656.png)
