### ISSUE TITLE
Editar un newspaper ya publicado peta pero no como deberia

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#38]
Tras crearme un newspaper un publicarlo, por url lo intente editar y si me dejo entrar en la vista para editaar (lo correcto seria que no ya que podria verse informacion sensible del newspaper que un usuario normal no deberia ver) y ademas al darle a save me peta : 
![image](https://user-images.githubusercontent.com/33448873/38497388-3e442540-3c01-11e8-87aa-d79b1024aec4.png)

**Comment by fraagucan2** [comment]
falla por el mensaje que hay que añadirlo

**Comment by fraagucan2** [comment]
Solucionado!

![imagen](https://user-images.githubusercontent.com/22836642/38503898-9cc53f0c-3c13-11e8-9162-f536f8915308.png)
