### ISSUE TITLE
Cuando intento publicar un newspaper con articles que no estan a final mode se publica automaticamente el newspaper y sus articulos asociados, ¿eso deberia ser asi?

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#40]
En ningun lado se especifica eso asi

**Comment by JJCCGGRR24** [comment]
y realmente en bd no se pone a finalmode el article pero en la columna aparece que si esta a final mode, y el newspaper si que se publica

**Comment by fraagucan2** [comment]
Solucionado, se ha añadido el if para que no actualice las fechas y lo publique si no estan todos los articulos en modo final.

![imagen](https://user-images.githubusercontent.com/22836642/38502376-7bd37cd6-3c0f-11e8-9c7c-37c4954e8d78.png)
