### ISSUE TITLE
No veo el requisito 17.1 en el header no se si estará o no

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#42]
17. An actor who is authenticated as an administrator must be able to:
     1. Manage a list of taboo words.

**Comment by fraagucan2** [comment]
Es pinchando en "taboo words"

**Comment by fraagucan2** [comment]
![imagen](https://user-images.githubusercontent.com/22836642/38502467-bfd30e2e-3c0f-11e8-8037-e70a5641e3f0.png)

**Comment by fraagucan2** [comment]
Voy a cambiar el header para que quede mas claro

**Comment by fraagucan2** [comment]
![imagen](https://user-images.githubusercontent.com/22836642/38502601-20d160f4-3c10-11e8-9f87-e8cd1418312e.png)

**Comment by JJCCGGRR24** [comment]
Perfecto compañero
