### ISSUE TITLE
Estando subscrito al periodico aparece el boton para subscribirme

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#45]
El customer 74 esta subscrito al newspaper 77 y aun asi aparece el boton para subscribirme. Aun asi deberia de controlarse para que no se pueda hacer tampoco por URL.

![imagen](https://user-images.githubusercontent.com/22836642/38504637-7a7ee086-3c15-11e8-9657-6e1a02588c12.png)

**Comment by JJCCGGRR24** [comment]
por url esta capado, aparece la vista y puedes darle a save, pero no te deja, lo que si yo diria de personalizar mas el error, da un error in database normal

**Comment by JJCCGGRR24** [comment]
añadido por controlador una lista con los periodicos a los que esta suscrito el customer, pasada a la vista con un contains ver si debe aparecerle el enlace en ese newspaper o no
