### ISSUE TITLE
No estoy seguro de si el 13 esta hecho, no lo logro ver, si es asi que se manifieste su autor y diga donde sta

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#51]
13. When displaying a newspaper, the system must first display its title, its description, its picture
(if any) and a table of contents that must include the title, the writer, and the summary
of each article in that newspaper. Clicking on the title must allow to navigate to the corresponding
article and clicking on the writer must allow to display his or her profile. It’d be
very appreciated if only the first few lines of the summaries were shown, so that they are
fully shown when the actor clicks on them.

**Comment by JJCCGGRR24** [comment]
o puede ser que con los datos que hay en el populate no se pueda comprobar

**Comment by fraagucan2** [comment]
![imagen](https://user-images.githubusercontent.com/22836642/38552129-71136b60-3cbb-11e8-9ff3-fd0a293575ed.png)

**Comment by fraagucan2** [comment]
Esto es lo que no encontrais?
