### ISSUE TITLE
Al registrarme como user redireccion incorrecta

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#55]
Me registro correctamente como usuario y al registrarme me redirige al login y al loguearme:

![imagen](https://user-images.githubusercontent.com/22836642/38558674-2359f144-3cd1-11e8-82a4-4291932e3f6a.png)

**Comment by JJCCGGRR24** [comment]
hechooo

**Comment by JJCCGGRR24** [comment]
puse q te rediriga al login

**Comment by fraagucan2** [comment]
Pasa lo mismo con customer @JJCCGGRR24

**Comment by fraagucan2** [comment]
Alomejor si utilizan las misma vista queda solucionado

**Comment by JJCCGGRR24** [comment]
ya lo cambie por eso cerre la issue, era q en el controlador la direccion estaba mal
