### ISSUE TITLE
En vista de users->articles aparecen los articulos de periodicos no publicados

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#56]
Al pinchar en users y darle a ver los articulos de un user aparecen los todos los articulos en modo final suyos aunque el periodico no este publicado.

![imagen](https://user-images.githubusercontent.com/22836642/38559872-734642d6-3cd4-11e8-99e8-70ff0fe9044f.png)

Y segun este requisito: List the users of the system and display their profiles, which must include their personal data and the list of articles that they have written as long as they are published in a newspaper.
Interpreto que debe estar publicado el periodico.

**Comment by JJCCGGRR24** [comment]
ponemos el a.newspaper.publicationDate !=null y palante

**Comment by fraagucan2** [comment]
Ademas no aparecen los articulos cuyo newspaper es privado y creo q deberian de aparecer

**Comment by JJCCGGRR24** [comment]
correcto, creo que si, esa parte la remodele yo y me volveria a confundir entre customer y user
