### ISSUE TITLE
Al pinchas en Articles->All solo aparece un article

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#57]
Supongo que puede ser porque es el unico public, si es asi cambiar el nombre del header de "all" por "public articles" o algo asi. O sino mostrarlos todos los que su periodico este publicado.

![imagen](https://user-images.githubusercontent.com/22836642/38560598-44c4cac0-3cd6-11e8-9d84-1c0e520e755d.png)

**Comment by JJCCGGRR24** [comment]
efectivamente solo sale uno y porque añadi yo ahora al populate de la forma q estan metidos no se llegaban a mostrar ninguno

**Comment by JJCCGGRR24** [comment]
y veo poner publicados ya q no dice en ningun lado que sean todos, sino publicados
2. List the newspapers that are published and browse their articles.
