### ISSUE TITLE
Quitar buscador de my newspaper

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#58]
Quitar buscador de my newspapers porque no busca entre mis newspapers sino en todos los publicados porq tambien se utiliza esta vista para el "Periodicos publicados" y puede llevar a confusion. Lo suyo seria q el buscados solo apareciera en la vista de "periodicos publicados".

![imagen](https://user-images.githubusercontent.com/22836642/38561055-53fee3f8-3cd7-11e8-8f63-48dc348a2433.png)

**Comment by GuillermoCasalCaro** [comment]
solucionado
