### ISSUE TITLE
Imagenes al crear un articulo

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#59]
Si en las imagenes del articulo pongo:
![imagen](https://user-images.githubusercontent.com/22836642/38561270-e2a4b5f6-3cd7-11e8-9a4d-97b9c188ed68.png)
(Es decir: poner una imagen acabado en una "," se crea una entrada en la base de datos con una "imagen" vacia"
![imagen](https://user-images.githubusercontent.com/22836642/38561300-fc534c60-3cd7-11e8-9e9a-8430014af986.png)

**Comment by GuillermoCasalCaro** [comment]
Me pongo con esto

**Comment by GuillermoCasalCaro** [comment]
@EachNotBlank lo soluciona
