### ISSUE TITLE
Redireccion incorrecta

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#62]
Al borrar un chirp o un newspaper redirecciona a la vista de todos los chirp/newspapers y deberia de mostrar la lista de los chirp/newspaper con palabras tabues de nuevo.

**Comment by JJCCGGRR24** [comment]
bueno eso es a gusto de cada uno, no dice donde te tiene que llevar, yo veo bien como esta

**Comment by JJCCGGRR24** [comment]
si quieres taboolear 5 newspaper seguidos es incodioso tener q volver a la otra vista todo el rato, de la forma actual cuando el admin decida que ya ha terminado de taboolear puede ir a la vista de la lista de taboo y ver lo que quiera ahi
