### ISSUE TITLE
asegurarse de que los newspapers privados no se muestran cuando no se debe al entrar desde los volumenes

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#68]
tal y como lo tenemos creo que no se cumple

**Comment by JJCCGGRR24** [comment]
1.
List the volumes in the system and browse their newspapers as long as they are
authorised (for instance, a private newspaper cannot be fully displayed to
unauthenticated actors).
2

**Comment by GuillermoCasalCaro** [comment]
Eso significa que se muestren pero capados como en el 1.0. Debería funcionar bien desde la entrega anterior.
