### ISSUE TITLE
vista rara en la tabla de publicaciones con taboo words

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#72]
![image](https://user-images.githubusercontent.com/33448873/39535030-2e19fe26-4e33-11e8-9a00-660ff89b73b6.png)

**Comment by GuillermoCasalCaro** [comment]
asi la hice, por parecerse un poco mas a twitter, no tiene nada malo la CREATIVIDAD aunque algunos estéis faltos de ella
