### ISSUE TITLE
he borrado todas las palabras taboo y me siguen apareciendo chirps con taboo words

### ISSUE THREAD

**Issue by JJCCGGRR24** [JJCCGGRR24/Firulais-2.0#73]
![image](https://user-images.githubusercontent.com/33448873/39535125-6bddb57c-4e33-11e8-9a2c-0babf4ac7eb1.png)

**Comment by JJCCGGRR24** [comment]
igual en articulos y anuncios

**Comment by GuillermoCasalCaro** [comment]
arreglao
