### ISSUE TITLE
Postal address y phone debe ser opcional

### ISSUE THREAD

**Issue by fraagucan2** [JJCCGGRR24/Firulais-2.0#74]
1. The system must support two kinds of actors, namely: administrators and users. It must
store the following information regarding them: their names, surnames, postal addresses
(OPTIONAL), phone numbers (OPTIONAL), and email addresses. Phone numbers are sequences
of digits that may optionally start with a “+”.

![imagen](https://user-images.githubusercontent.com/22836642/39538465-38fe4cca-4e3d-11e8-8967-9a48d6c508e0.png)

**Comment by GuillermoCasalCaro** [comment]
arreglao
